name: zadanie_flutter_softnauts
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  cupertino_icons: ^0.1.2
  provider:
  built_value:
  built_collection:
  flutter_bloc: ^1.0.0
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator:
  build_runner:
  analyzer:

flutter:
  uses-material-design: true
